# Generated by Django 3.1.3 on 2020-12-07 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('description_1', models.CharField(blank=True, max_length=300, null=True)),
                ('date_1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description_2', models.CharField(blank=True, max_length=300, null=True)),
                ('date_2', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description_3', models.CharField(blank=True, max_length=300, null=True)),
                ('date_3', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description_4', models.CharField(blank=True, max_length=300, null=True)),
                ('date_4', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description_5', models.CharField(blank=True, max_length=300, null=True)),
                ('date_5', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
